easy_admin:
  entities:
    User:
      class: App\Entity\User
      label: 'Client'
      list:
        title: 'Client'
        fields: ['name', 'firstName', 'email', 'bookings', 'number']
      form:
        fields:
          - {property: 'name'}
          - {property: 'firstName', type_options: { required: false }}
          - {property: 'email',  type: 'email'}
          - {property: 'number'}
        form_options: { validation_groups: false }
      new:
        fields:
            - {property: 'name'}
            - {property: 'firstName', type_options: { required: false }}
            - {property: 'email',  type: 'email'}
            - {property: 'number'}
            - {property: 'hash', label: 'mot de passe'}
      edit:
        fields:
            - {property: 'name'}
            - {property: 'firstName', type_options: { required: false }}
            - {property: 'email',  type: 'email'}
            - {property: 'number'}

      search:
        fields: ['name', 'email', 'number']
